# Generated by Django 2.1.3 on 2019-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('preferred_category', models.CharField(choices=[('tc', 'technology'), ('sp', 'sports'), ('ph', 'philosophy'), ('pl', 'politics')], max_length=200)),
                ('profile_photo', models.ImageField(upload_to='', verbose_name=models.CharField(max_length=200))),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
