# Generated by Django 2.1.3 on 2019-02-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190213_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
