# Generated by Django 2.1.3 on 2019-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, upload_to='', width_field=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tc', 'technology'), ('sp', 'sports'), ('ph', 'philosophy'), ('pl', 'politics')], max_length=30),
        ),
    ]
